Imported Debian patch 9.06-3

diff --git a/debian/rxvt-unicode-base.preinst b/debian/rxvt-unicode-base.preinst
--- a/debian/rxvt-unicode-base.preinst
+++ b/debian/rxvt-unicode-base.preinst
@@ -1,8 +1,11 @@
 #!/bin/sh -e
 
 if [ "$1" = upgrade ]; then
-    # clean up after old versions
-    update-alternatives --remove x-terminal-emulator /usr/bin/urxvtcd
+    # clean up after old versions, unless the admin chose urxvtcd
+    if ! update-alternatives --query x-terminal-emulator | grep -q \
+            '^Value: /usr/bin/urxvtcd$'; then
+        update-alternatives --remove x-terminal-emulator /usr/bin/urxvtcd
+    fi
 fi
 
 #DEBHELPER#
